"""Add date created to financial quarters

Revision ID: 0a7eb7e4b0ba
Revises: 0eb4cd0dc8a8
Create Date: 2024-12-31 23:25:49.791846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7eb7e4b0ba'
down_revision: Union[str, None] = '0eb4cd0dc8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_quarters', sa.Column('date_created', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_quarters', 'date_created')
    # ### end Alembic commands ###
