"""change product_id column to product_code

Revision ID: 2b5846f78671
Revises: 0a7eb7e4b0ba
Create Date: 2024-12-31 23:51:40.317607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5846f78671'
down_revision: Union[str, None] = '0a7eb7e4b0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_discounts', sa.Column('product_code', sa.String(length=5), nullable=False))
    op.drop_constraint('product_discounts_product_id_fkey', 'product_discounts', type_='foreignkey')
    op.create_foreign_key(None, 'product_discounts', 'products', ['product_code'], ['product_code'])
    op.drop_column('product_discounts', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_discounts', sa.Column('product_id', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_discounts', type_='foreignkey')
    op.create_foreign_key('product_discounts_product_id_fkey', 'product_discounts', 'products', ['product_id'], ['product_code'])
    op.drop_column('product_discounts', 'product_code')
    # ### end Alembic commands ###
