"""altering relationship mappings in models

Revision ID: 3cdc99604e5f
Revises: b7e9127fd9ca
Create Date: 2025-01-01 15:40:53.191904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdc99604e5f'
down_revision: Union[str, None] = 'b7e9127fd9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
