"""upgrade products and discount relationships

Revision ID: 4968f0177cf8
Revises: 7f8193bf1fe6
Create Date: 2025-01-01 14:33:42.825258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4968f0177cf8'
down_revision: Union[str, None] = '7f8193bf1fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
