"""altering foreignkey for product discount

Revision ID: b7e9127fd9ca
Revises: 6055bc3840ef
Create Date: 2025-01-01 14:45:23.276586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e9127fd9ca'
down_revision: Union[str, None] = '6055bc3840ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_discounts', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_constraint('product_discounts_product_code_fkey', 'product_discounts', type_='foreignkey')
    op.create_foreign_key(None, 'product_discounts', 'products', ['product_id'], ['id'])
    op.drop_column('product_discounts', 'product_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_discounts', sa.Column('product_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_discounts', type_='foreignkey')
    op.create_foreign_key('product_discounts_product_code_fkey', 'product_discounts', 'products', ['product_code'], ['product_code'])
    op.drop_column('product_discounts', 'product_id')
    # ### end Alembic commands ###
